apps:
  - script   : ./dist/index.js
    name     : 'api-app'    
  - script : ./dist/worker.js
    name   : 'worker'
    watch  : true
    env    :
      NODE_ENV: development
    env_production:
      NODE_ENV: production